sudo: false
language: ruby
branches:
  only:
    - master
rvm:
  - 2.2.5
  - 2.3.1
script: bundle exec rake build
notifications:
  slack:
    secure: fe0zpCNfsuzpjcQJrPiG4hmCfc5sXYYw3BLSyKnFXl0ykUz9AOZ0VDz9PUoX8F/7GY0ro4H/pA3ozX2moNxKkcV+GGInmqOswBAzUuSFErQOuyD5nYPsIicLjSTP83Lr1FiXZQ4GL7YJ9fa9VJ9hIMpdN71500dFPInPqfQUhNk=
